#!/bin/bash
DEST="$(dirname "$0")/public/dishes"
mkdir -p "$DEST"

dl() { curl -s -L -o "$DEST/$(basename "$1")" "$1" && echo "ok: $(basename "$1")" || echo "fail: $1"; }

dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Gunpowder-Gobhi.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PANEER-SCHNITZEL.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/SIZZLING-PANEER.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Zeitooni-Malai-Paneer.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/HARIYALI-KEBAB.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Soya-Seekh-Kebab.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/RAJASTHANI-MIRCHI-VADA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Entrees_Indian-Chips-Dips_01-1024x768.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PANI-POORI.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/ONION-BHAJI.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/TRIANGLE-SAMOSA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/STREET-SAMOSA-CHAAT.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PAPADI-CHAAT.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PALAK-PATTA-CHAAT.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Chefs-Special-Shahi-Murgh-Tikka.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHICKEN-65.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/MURGH-ABEER-TIKKA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Entree_Saffron-Chicken-Tikka_01-ri381p5s1zwap0rpedu6zn6dx5gkaxtcbcqyo272f4.jpg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Lahori-Boti-Tikka.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHARCOAL-TANDOORI-CHICKEN.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHEFS-SPECIAL-LAMB-CHOPS.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Entree_Achari-Seekh-Kebab_01-ri385zbb6trbl2jse8h0ck9zcccrdatbkjqldfui2o.jpg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/KAKORI-KEBAB.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Chefs-Special-Tandoori-Salmon-.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/SEMOLINA-CRUSTED-PRAWNS.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/AMRITSARI-FISH.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHEFS-SPECIAL-CHEESE-BUTTER-MASALA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/KAJU-MASALA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Vegetables-Korma.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Aloo-Gobhi.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/BHINDI-DO-PYAZA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/BAINGAN-MASALA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PALAK-PANEER.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PANEER-TAKA-TAK.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Veg-Jalfrezi.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Mix-Vegetable-Curry-.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Malai-Kofta.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/KADHAI-PANEER.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Kadhai-Mushroom-.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/DAAL-MAKHANI.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/LASOONI-DAAL-TADKA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Chefs-Special-TGP-Dragon-Chicken-Curry.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Chicken-Dhanshak.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHICKEN-SAAG-WALA-32.90.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/BUTTER-CHICKEN.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Mains_Chicken-Tikka-Masala_04-scaled-ri388vne9fq5dsc8gzkljby5a42i3pbiyw5hn5jsw0.jpg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Mains_Chicken-Vindaloo_03-scaled-ri389289l9z5n22oekezisadft62ll1nbspw03a1og.jpg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHEFS-SPECIAL-LAMB-SHANK-MASALA.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Kashmiri-Rogan-Josh.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Lamb-Saag.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Lamb-Bhoona.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/cocunut-lamb-curry.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Goat-Pepper-Fry.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Handi-Goat-Masala.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Chefs-Special-Butter-Salmon.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Masala-Fish-Curry.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Mains_Chilli-Garlic-Prawns-ri9mgq5y195xu9s19geshx7gcibn47i13xhq612q68.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/SAFFRON-FLAVOURED-BASMATI-RICE.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Jeera-Rice.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/VEGETARIAN-DUM-PARDA-BIRYANI-GF-Available-29.90.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/CHICKEN-DUM-PARDA-BIRYANI-GF-Available-31.90.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/GOAT-DUM-PARDA-BIRYANI.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/LAMB-DUM-PARDA-BIRYANI-.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/PRAWN-DUM-PARDA-BIRYANI.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Chef_s-Special-Keema-Naan-ri9mx7a3tppvc7ui22sdp9jb6n4917wnph53zmnb40.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Bread_Classic-Naan-ri9mstd7xjpp5q7vo6j22ddvdwql42hr3rjjd55g5c.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Wholemeal-Roti.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Butter-Naan.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Chilli-Garlic-Naan.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Chilli-Naan.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Bread_Cheese-Naan-ri9mr812cnj7hij5yzqtc9ur5el72j64jvqx39igow.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Cheese-Garlic-Naan.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Peshawari-Naan.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Amritsari-Kulcha.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Lachha-Butter-Paratha.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Missi-Roti.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/MASALA-PAPAD.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Garden-Green-Salad.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Lacha-Pyaz.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Sides_Cucumber-Raita-ri38cvgpb370q4jc57qimtno62dnte6ginys2hmkg0.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Mint-Sauce.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Mango-Chutney.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Mixed-Pickle.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Sides_Yoghurt_01-scaled-ri38dg55hfzbtjpasgob5oft8jjqiqgjxibgmkrwn4.jpg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Mains_Veg-Kolhapuri-ri9n03m6wbop4xmy4tvyw17h4etzrmev3tk09cclxc.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Mains_Cheese-Butter-Masala-ri9mzqgfk32a4b7672wxqirxtph54h5tht1wwa82q8.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/KULFI-KESAR-MANGO-_-PISTACHIO.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Walnut-Brownie-Choco-Heaven-with-Ice-Cream.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2025/04/Kesari-Rasmalai.png" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/elementor/thumbs/Dessert_Gulab-Jamun-ri38l5fjhkiwyiiitaj938gsh7l0lg1dbmrp77crnk.jpeg" &
dl "https://www.thegrandpalace.com.au/wp-content/uploads/2026/01/Dessert_Lassi_AllThree_01-979x1024.jpeg" &

wait
echo "=== DONE: $(ls "$DEST" | wc -l) files ==="
