/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BeveragesRouteImport } from './routes/beverages'
import { Route as BirthdayPackageRouteImport } from './routes/birthday-package'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookATableRouteImport } from './routes/book-a-table'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiftCardRouteImport } from './routes/gift-card'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LunchSpecialRouteImport } from './routes/lunch-special'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OfficeCateringRouteImport } from './routes/office-catering'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SetMenuRouteImport } from './routes/set-menu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VenueCateringRouteImport } from './routes/venue-catering'
import { Route as VenueForHireRouteImport } from './routes/venue-for-hire'
import { Route as WhatsOnRouteImport } from './routes/whats-on'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminGuidesRouteImport } from './routes/admin.guides'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSiteImagesRouteImport } from './routes/admin.site-images'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuMenuTypeRouteImport } from './routes/menu.$menuType'
import { Route as MenuALaCarteRouteImport } from './routes/menu.a-la-carte'
import { Route as WhatsOnIndexRouteImport } from './routes/whats-on.index'
import { Route as WhatsOnSlugRouteImport } from './routes/whats-on.$slug'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin.leads.index'
import { Route as AdminLeadsTypeRouteImport } from './routes/admin.leads.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BeveragesRoute = BeveragesRouteImport.update({
  id: '/beverages',
  path: '/beverages',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayPackageRoute = BirthdayPackageRouteImport.update({
  id: '/birthday-package',
  path: '/birthday-package',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookATableRoute = BookATableRouteImport.update({
  id: '/book-a-table',
  path: '/book-a-table',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardRoute = GiftCardRouteImport.update({
  id: '/gift-card',
  path: '/gift-card',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LunchSpecialRoute = LunchSpecialRouteImport.update({
  id: '/lunch-special',
  path: '/lunch-special',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeCateringRoute = OfficeCateringRouteImport.update({
  id: '/office-catering',
  path: '/office-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SetMenuRoute = SetMenuRouteImport.update({
  id: '/set-menu',
  path: '/set-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueCateringRoute = VenueCateringRouteImport.update({
  id: '/venue-catering',
  path: '/venue-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueForHireRoute = VenueForHireRouteImport.update({
  id: '/venue-for-hire',
  path: '/venue-for-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsOnRoute = WhatsOnRouteImport.update({
  id: '/whats-on',
  path: '/whats-on',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteImagesRoute = AdminSiteImagesRouteImport.update({
  id: '/site-images',
  path: '/site-images',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuMenuTypeRoute = MenuMenuTypeRouteImport.update({
  id: '/$menuType',
  path: '/$menuType',
  getParentRoute: () => MenuRoute,
} as any)
const MenuALaCarteRoute = MenuALaCarteRouteImport.update({
  id: '/a-la-carte',
  path: '/a-la-carte',
  getParentRoute: () => MenuRoute,
} as any)
const WhatsOnIndexRoute = WhatsOnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WhatsOnRoute,
} as any)
const WhatsOnSlugRoute = WhatsOnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WhatsOnRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminLeadsTypeRoute = AdminLeadsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => AdminLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/beverages': typeof BeveragesRoute
  '/birthday-package': typeof BirthdayPackageRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-table': typeof BookATableRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/gift-card': typeof GiftCardRoute
  '/guides': typeof GuidesRouteWithChildren
  '/lunch-special': typeof LunchSpecialRoute
  '/menu': typeof MenuRouteWithChildren
  '/office-catering': typeof OfficeCateringRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/set-menu': typeof SetMenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/venue-catering': typeof VenueCateringRoute
  '/venue-for-hire': typeof VenueForHireRoute
  '/whats-on': typeof WhatsOnRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/site-images': typeof AdminSiteImagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/menu/$menuType': typeof MenuMenuTypeRoute
  '/menu/a-la-carte': typeof MenuALaCarteRoute
  '/whats-on/$slug': typeof WhatsOnSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/whats-on/': typeof WhatsOnIndexRoute
  '/admin/leads/$type': typeof AdminLeadsTypeRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beverages': typeof BeveragesRoute
  '/birthday-package': typeof BirthdayPackageRoute
  '/book-a-table': typeof BookATableRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/gift-card': typeof GiftCardRoute
  '/lunch-special': typeof LunchSpecialRoute
  '/office-catering': typeof OfficeCateringRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/set-menu': typeof SetMenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/venue-catering': typeof VenueCateringRoute
  '/venue-for-hire': typeof VenueForHireRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/site-images': typeof AdminSiteImagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/menu/$menuType': typeof MenuMenuTypeRoute
  '/menu/a-la-carte': typeof MenuALaCarteRoute
  '/whats-on/$slug': typeof WhatsOnSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/menu': typeof MenuIndexRoute
  '/whats-on': typeof WhatsOnIndexRoute
  '/admin/leads/$type': typeof AdminLeadsTypeRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/beverages': typeof BeveragesRoute
  '/birthday-package': typeof BirthdayPackageRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-table': typeof BookATableRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/gift-card': typeof GiftCardRoute
  '/guides': typeof GuidesRouteWithChildren
  '/lunch-special': typeof LunchSpecialRoute
  '/menu': typeof MenuRouteWithChildren
  '/office-catering': typeof OfficeCateringRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/set-menu': typeof SetMenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/venue-catering': typeof VenueCateringRoute
  '/venue-for-hire': typeof VenueForHireRoute
  '/whats-on': typeof WhatsOnRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/site-images': typeof AdminSiteImagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/menu/$menuType': typeof MenuMenuTypeRoute
  '/menu/a-la-carte': typeof MenuALaCarteRoute
  '/whats-on/$slug': typeof WhatsOnSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/whats-on/': typeof WhatsOnIndexRoute
  '/admin/leads/$type': typeof AdminLeadsTypeRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/beverages'
    | '/birthday-package'
    | '/blog'
    | '/book-a-table'
    | '/career'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/gift-card'
    | '/guides'
    | '/lunch-special'
    | '/menu'
    | '/office-catering'
    | '/robots.txt'
    | '/set-menu'
    | '/sitemap.xml'
    | '/terms'
    | '/venue-catering'
    | '/venue-for-hire'
    | '/whats-on'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/guides'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/pages'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/site-images'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/menu/$menuType'
    | '/menu/a-la-carte'
    | '/whats-on/$slug'
    | '/admin/'
    | '/blog/'
    | '/guides/'
    | '/menu/'
    | '/whats-on/'
    | '/admin/leads/$type'
    | '/admin/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beverages'
    | '/birthday-package'
    | '/book-a-table'
    | '/career'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/gift-card'
    | '/lunch-special'
    | '/office-catering'
    | '/robots.txt'
    | '/set-menu'
    | '/sitemap.xml'
    | '/terms'
    | '/venue-catering'
    | '/venue-for-hire'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/pages'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/site-images'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/menu/$menuType'
    | '/menu/a-la-carte'
    | '/whats-on/$slug'
    | '/admin'
    | '/blog'
    | '/guides'
    | '/menu'
    | '/whats-on'
    | '/admin/leads/$type'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/beverages'
    | '/birthday-package'
    | '/blog'
    | '/book-a-table'
    | '/career'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/gift-card'
    | '/guides'
    | '/lunch-special'
    | '/menu'
    | '/office-catering'
    | '/robots.txt'
    | '/set-menu'
    | '/sitemap.xml'
    | '/terms'
    | '/venue-catering'
    | '/venue-for-hire'
    | '/whats-on'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/guides'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/pages'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/site-images'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/menu/$menuType'
    | '/menu/a-la-carte'
    | '/whats-on/$slug'
    | '/admin/'
    | '/blog/'
    | '/guides/'
    | '/menu/'
    | '/whats-on/'
    | '/admin/leads/$type'
    | '/admin/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeveragesRoute: typeof BeveragesRoute
  BirthdayPackageRoute: typeof BirthdayPackageRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookATableRoute: typeof BookATableRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  GiftCardRoute: typeof GiftCardRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LunchSpecialRoute: typeof LunchSpecialRoute
  MenuRoute: typeof MenuRouteWithChildren
  OfficeCateringRoute: typeof OfficeCateringRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SetMenuRoute: typeof SetMenuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VenueCateringRoute: typeof VenueCateringRoute
  VenueForHireRoute: typeof VenueForHireRoute
  WhatsOnRoute: typeof WhatsOnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beverages': {
      id: '/beverages'
      path: '/beverages'
      fullPath: '/beverages'
      preLoaderRoute: typeof BeveragesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-package': {
      id: '/birthday-package'
      path: '/birthday-package'
      fullPath: '/birthday-package'
      preLoaderRoute: typeof BirthdayPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-table': {
      id: '/book-a-table'
      path: '/book-a-table'
      fullPath: '/book-a-table'
      preLoaderRoute: typeof BookATableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-card': {
      id: '/gift-card'
      path: '/gift-card'
      fullPath: '/gift-card'
      preLoaderRoute: typeof GiftCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lunch-special': {
      id: '/lunch-special'
      path: '/lunch-special'
      fullPath: '/lunch-special'
      preLoaderRoute: typeof LunchSpecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-catering': {
      id: '/office-catering'
      path: '/office-catering'
      fullPath: '/office-catering'
      preLoaderRoute: typeof OfficeCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-menu': {
      id: '/set-menu'
      path: '/set-menu'
      fullPath: '/set-menu'
      preLoaderRoute: typeof SetMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue-catering': {
      id: '/venue-catering'
      path: '/venue-catering'
      fullPath: '/venue-catering'
      preLoaderRoute: typeof VenueCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue-for-hire': {
      id: '/venue-for-hire'
      path: '/venue-for-hire'
      fullPath: '/venue-for-hire'
      preLoaderRoute: typeof VenueForHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-on': {
      id: '/whats-on'
      path: '/whats-on'
      fullPath: '/whats-on'
      preLoaderRoute: typeof WhatsOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-images': {
      id: '/admin/site-images'
      path: '/site-images'
      fullPath: '/admin/site-images'
      preLoaderRoute: typeof AdminSiteImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/$menuType': {
      id: '/menu/$menuType'
      path: '/$menuType'
      fullPath: '/menu/$menuType'
      preLoaderRoute: typeof MenuMenuTypeRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/a-la-carte': {
      id: '/menu/a-la-carte'
      path: '/a-la-carte'
      fullPath: '/menu/a-la-carte'
      preLoaderRoute: typeof MenuALaCarteRouteImport
      parentRoute: typeof MenuRoute
    }
    '/whats-on/': {
      id: '/whats-on/'
      path: '/'
      fullPath: '/whats-on/'
      preLoaderRoute: typeof WhatsOnIndexRouteImport
      parentRoute: typeof WhatsOnRoute
    }
    '/whats-on/$slug': {
      id: '/whats-on/$slug'
      path: '/$slug'
      fullPath: '/whats-on/$slug'
      preLoaderRoute: typeof WhatsOnSlugRouteImport
      parentRoute: typeof WhatsOnRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/leads/$type': {
      id: '/admin/leads/$type'
      path: '/$type'
      fullPath: '/admin/leads/$type'
      preLoaderRoute: typeof AdminLeadsTypeRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
  }
}

interface AdminLeadsRouteChildren {
  AdminLeadsTypeRoute: typeof AdminLeadsTypeRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsTypeRoute: AdminLeadsTypeRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSiteImagesRoute: typeof AdminSiteImagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGuidesRoute: AdminGuidesRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSiteImagesRoute: AdminSiteImagesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface MenuRouteChildren {
  MenuMenuTypeRoute: typeof MenuMenuTypeRoute
  MenuALaCarteRoute: typeof MenuALaCarteRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuMenuTypeRoute: MenuMenuTypeRoute,
  MenuALaCarteRoute: MenuALaCarteRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

interface WhatsOnRouteChildren {
  WhatsOnSlugRoute: typeof WhatsOnSlugRoute
  WhatsOnIndexRoute: typeof WhatsOnIndexRoute
}

const WhatsOnRouteChildren: WhatsOnRouteChildren = {
  WhatsOnSlugRoute: WhatsOnSlugRoute,
  WhatsOnIndexRoute: WhatsOnIndexRoute,
}

const WhatsOnRouteWithChildren =
  WhatsOnRoute._addFileChildren(WhatsOnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BeveragesRoute: BeveragesRoute,
  BirthdayPackageRoute: BirthdayPackageRoute,
  BlogRoute: BlogRouteWithChildren,
  BookATableRoute: BookATableRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  GiftCardRoute: GiftCardRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LunchSpecialRoute: LunchSpecialRoute,
  MenuRoute: MenuRouteWithChildren,
  OfficeCateringRoute: OfficeCateringRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SetMenuRoute: SetMenuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VenueCateringRoute: VenueCateringRoute,
  VenueForHireRoute: VenueForHireRoute,
  WhatsOnRoute: WhatsOnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
